project:
  type: website

website:
  title: "assignment-3-cnd34"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Cody Dettlaff

format:
  html:
    theme:
      - solar
      - brand
    css: styles.css
    toc: true
output-dir: docs




